//-----------------------DRIVER-------------------------

export const ADD_DRIVER_ERROR = "ADD_DRIVER_ERROR"
export const ADD_DRIVER_LOADING = "ADD_DRIVER_LOADING"
export const ADD_DRIVER_SUCCESS = "ADD_DRIVER_SUCCESS"

export const DELETE_DRIVER_LOADING = "DELETE_DRIVER_LOADING"
export const DELETE_DRIVER_ERROR = "DELETE_DRIVER_ERROR"
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS"

export const EDIT_DRIVER_LOADING = "EDIT_DRIVER_LOADING"
export const EDIT_DRIVER_ERROR = "EDIT_DRIVER_ERROR"
export const EDIT_DRIVER_SUCCESS = "EDIT_DRIVER_SUCCESS"

export const FETCH_DRIVER_ERROR = "FETCH_DRIVER_ERROR"
export const FETCH_DRIVER_SUCCESS = "FETCH_DRIVER_SUCCESS"
export const FETCH_DRIVER_LOADING = "FETCH_DRIVER_LOADING"

export const USER_CITY_SORTED = "USER_CITY_SORTED"

//-----------------------DISPATCHER---------------------

export const ADD_DISPATCHER_ERROR = "ADD_DISPATCHER_ERROR"
export const ADD_DISPATCHER_LOADING = "ADD_DISPATCHER_LOADING"
export const ADD_DISPATCHER_SUCCESS = "ADD_DISPATCHER_SUCCESS"

export const DELETE_DISPATCHER_LOADING = "DELETE_DISPATCHER_LOADING"
export const DELETE_DISPATCHER_ERROR = "DELETE_DISPATCHER_ERROR"
export const DELETE_DISPATCHER_SUCCESS = "DELETE_DISPATCHER_SUCCESS"

export const EDIT_DISPATCHER_LOADING = "EDIT_DISPATCHER_LOADING"
export const EDIT_DISPATCHER_ERROR = "EDIT_DISPATCHER_ERROR"
export const EDIT_DISPATCHER_SUCCESS = "EDIT_DISPATCHER_SUCCESS"

export const FETCH_DISPATCHER_ERROR = "FETCH_DISPATCHER_ERROR"
export const FETCH_DISPATCHER_SUCCESS = "FETCH_DISPATCHER_SUCCESS"
export const FETCH_DISPATCHER_LOADING = "FETCH_DISPATCHER_LOADING"


//-----------------------CLIENT-----------------------

export const ADD_CLIENT_ERROR = "ADD_CLIENT_ERROR"
export const ADD_CLIENT_LOADING = "ADD_CLIENT_LOADING"
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS"

export const DELETE_CLIENT_LOADING = "DELETE_CLIENT_LOADING"
export const DELETE_CLIENT_ERROR = "DELETE_CLIENT_ERROR"
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS"

export const EDIT_CLIENT_LOADING = "EDIT_CLIENT_LOADING"
export const EDIT_CLIENT_ERROR = "EDIT_CLIENT_ERROR"
export const EDIT_CLIENT_SUCCESS = "EDIT_CLIENT_SUCCESS"

export const FETCH_CLIENT_ERROR = "FETCH_CLIENT_ERROR"
export const FETCH_CLIENT_SUCCESS = "FETCH_CLIENT_SUCCESS"
export const FETCH_CLIENT_LOADING = "FETCH_CLIENT_LOADING"

//-----------------------CAR-----------------------

export const ADD_CAR_ERROR = "ADD_CAR_ERROR"
export const ADD_CAR_LOADING = "ADD_CAR_LOADING"
export const ADD_CAR_SUCCESS = "ADD_CAR_SUCCESS"

export const DELETE_CAR_LOADING = "DELETE_CAR_LOADING"
export const DELETE_CAR_ERROR = "DELETE_CAR_ERROR"
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS"

export const EDIT_CAR_LOADING = "EDIT_CAR_LOADING"
export const EDIT_CAR_ERROR = "EDIT_CAR_ERROR"
export const EDIT_CAR_SUCCESS = "EDIT_CAR_SUCCESS"

export const FETCH_CAR_ERROR = "FETCH_CAR_ERROR"
export const FETCH_CAR_SUCCESS = "FETCH_CAR_SUCCESS"
export const FETCH_CAR_LOADING = "FETCH_CAR_LOADING"


//-----------------------ORDER-----------------------

export const ADD_ORDER_ERROR = "ADD_ORDER_ERROR"
export const ADD_ORDER_LOADING = "ADD_ORDER_LOADING"
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS"

export const DELETE_ORDER_LOADING = "DELETE_ORDER_LOADING"
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"

export const EDIT_ORDER_LOADING = "EDIT_ORDER_LOADING"
export const EDIT_ORDER_ERROR = "EDIT_ORDER_ERROR"
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS"

export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR"
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
export const FETCH_ORDER_LOADING = "FETCH_ORDER_LOADING"

